// Template data for starter plans
// These are pre-configured wall layouts that users can start with

export interface PlanTemplate {
  id: string;
  name: string;
  description: string;
  preview: string;
  planData: Record<string, unknown> | null;
}

export const PLAN_TEMPLATES: PlanTemplate[] = [
  {
    id: "empty",
    name: "Plan Vierge",
    description: "Commencer avec un plan complètement vide",
    preview: "/templates/empty-preview.svg",
    planData: {
      // Empty plan data - current default behavior
      layers: {
        "11111111-1111-1111-1111-111111111111": {
          id: "11111111-1111-1111-1111-111111111111",
          altitude: 0,
          order: 0,
          opacity: 1,
          name: "default",
          visible: true,
          lines: {},
          holes: {},
          areas: {},
          items: {},
          vertices: {},
          selected: {},
        },
      },
      scene: {
        layers: ["11111111-1111-1111-1111-111111111111"],
        selectedLayer: "11111111-1111-1111-1111-111111111111",
      },
    },
  },
  {
    id: "square",
    name: "Plan Carré",
    description: "Plan carré de base (500m x 500m)",
    preview: "/templates/square-preview.svg",
    planData: {
      unit: "m",
      layers: {
        "11111111-1111-1111-1111-111111111111": {
          id: "11111111-1111-1111-1111-111111111111",
          altitude: 0,
          order: 0,
          opacity: 1,
          name: "default",
          visible: true,
          vertices: {
            "vertex-1": {
              id: "vertex-1",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1250,
              y: 750,
              lines: ["RKJ6ybEZNC", "F14nbPXGJk"],
              areas: [],
            },
            "vertex-2": {
              id: "vertex-2",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1750,
              y: 750,
              lines: ["RKJ6ybEZNC", "ahVjwJGnxh"],
              areas: [],
            },
            "vertex-3": {
              id: "vertex-3",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1750,
              y: 1250,
              lines: ["aHGRykxoTw", "ahVjwJGnxh"],
              areas: [],
            },
            "vertex-4": {
              id: "vertex-4",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1250,
              y: 1250,
              lines: ["aHGRykxoTw", "F14nbPXGJk"],
              areas: [],
            },
          },
          lines: {
            aHGRykxoTw: {
              id: "aHGRykxoTw",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["vertex-4", "vertex-3"],
              holes: [],
            },
            RKJ6ybEZNC: {
              id: "RKJ6ybEZNC",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["vertex-1", "vertex-2"],
              holes: [],
            },
            ahVjwJGnxh: {
              id: "ahVjwJGnxh",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["vertex-2", "vertex-3"],
              holes: [],
            },
            F14nbPXGJk: {
              id: "F14nbPXGJk",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["vertex-1", "vertex-4"],
              holes: [],
            },
          },
          holes: {},
          areas: {
            Fu1PxLq29cO: {
              id: "Fu1PxLq29cO",
              type: "area",
              prototype: "areas",
              name: "Zone",
              misc: {},
              selected: false,
              properties: {
                patternColor: "#F5F4F4",
                thickness: { length: 0 },
                texture: "none",
              },
              visible: true,
              vertices: ["vertex-2", "vertex-3", "vertex-4", "vertex-1"],
              holes: [],
            },
          },
          items: {},
          selected: {
            vertices: [],
            lines: [],
            holes: [],
            areas: [],
            items: [],
          },
        },
      },
      grids: {
        h1: {
          id: "h1",
          type: "horizontal-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
        v1: {
          id: "v1",
          type: "vertical-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
      },
      selectedLayer: "11111111-1111-1111-1111-111111111111",
      groups: {},
      width: 3000,
      height: 2000,
      meta: {},
      guides: { horizontal: {}, vertical: {}, circular: {} },
    },
  },
  {
    id: "rectangular",
    name: "Plan Rectangulaire",
    description: "Plan rectangulaire de base",
    preview: "/templates/rectangular-preview.svg",
    planData: {
      unit: "m",
      layers: {
        "11111111-1111-1111-1111-111111111111": {
          id: "11111111-1111-1111-1111-111111111111",
          altitude: 0,
          order: 0,
          opacity: 1,
          name: "default",
          visible: true,
          vertices: {
            "rect-vertex-1": {
              id: "rect-vertex-1",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1000,
              y: 767.7182520821407,
              lines: ["rect-wall-left", "_UF2bFX-pw"],
              areas: ["rect-area-1"],
            },
            "rect-vertex-2": {
              id: "rect-vertex-2",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1989.6552690174249,
              y: 767.7182520821407,
              lines: ["d_GQprHdSs", "_UF2bFX-pw"],
              areas: ["rect-area-1"],
            },
            "rect-vertex-3": {
              id: "rect-vertex-3",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1989.6552690174249,
              y: 1232.1993232932352,
              lines: ["d_GQprHdSs", "EM6hnITJny"],
              areas: ["rect-area-1"],
            },
            "rect-vertex-4": {
              id: "rect-vertex-4",
              type: "",
              prototype: "vertices",
              name: "",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1000,
              y: 1232.1993232932352,
              lines: ["rect-wall-left", "EM6hnITJny"],
              areas: ["rect-area-1"],
            },
          },
          lines: {
            "_UF2bFX-pw": {
              id: "_UF2bFX-pw",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["rect-vertex-1", "rect-vertex-2"],
              holes: [],
            },
            "rect-wall-left": {
              id: "rect-wall-left",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["rect-vertex-4", "rect-vertex-1"],
              holes: [],
            },
            d_GQprHdSs: {
              id: "d_GQprHdSs",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["rect-vertex-2", "rect-vertex-3"],
              holes: [],
            },
            EM6hnITJny: {
              id: "EM6hnITJny",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["rect-vertex-4", "rect-vertex-3"],
              holes: [],
            },
          },
          holes: {},
          areas: {
            "rect-area-1": {
              id: "rect-area-1",
              type: "area",
              prototype: "areas",
              name: "Zone",
              misc: {},
              selected: false,
              properties: {
                patternColor: "#F5F4F4",
                thickness: { length: 0 },
                texture: "none",
              },
              visible: true,
              vertices: [
                "rect-vertex-1",
                "rect-vertex-2",
                "rect-vertex-3",
                "rect-vertex-4",
              ],
              holes: [],
            },
          },
          items: {},
          selected: {
            vertices: [],
            lines: [],
            holes: [],
            areas: [],
            items: [],
          },
        },
      },
      grids: {
        h1: {
          id: "h1",
          type: "horizontal-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
        v1: {
          id: "v1",
          type: "vertical-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
      },
      selectedLayer: "11111111-1111-1111-1111-111111111111",
      groups: {},
      width: 3000,
      height: 2000,
      meta: {},
      guides: { horizontal: {}, vertical: {}, circular: {} },
    },
  },
  {
    id: "t-shape",
    name: "Plan en T",
    description: "Layout en forme de T avec couloir central",
    preview: "/templates/t-shape-preview.svg",
    planData: {
      unit: "m",
      layers: {
        "layer-1": {
          id: "layer-1",
          altitude: 0,
          order: 0,
          opacity: 1,
          name: "default",
          visible: true,
          vertices: {
            _z3Tpxi8Ibq: {
              id: "_z3Tpxi8Ibq",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 788.5355379974462,
              y: 1097.5588325016324,
              lines: ["RoEx_yqt1G", "DAB-5Viao2L"],
              areas: [],
            },
            InbPjbUTVTp: {
              id: "InbPjbUTVTp",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1599.2664330819252,
              y: 1097.5588325016324,
              lines: ["h4zteZPjvmB", "GMCmSNzgor"],
              areas: [],
            },
            RyNf_IIhaph: {
              id: "RyNf_IIhaph",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 788.5355379974462,
              y: 1296.6857190136097,
              lines: ["DAB-5Viao2L", "9Vyygqe59p"],
              areas: [],
            },
            Mtxn9_dUm6O: {
              id: "Mtxn9_dUm6O",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1095.759877187354,
              y: 596.896946414375,
              lines: ["f5C8DF6neE", "hjEMx7bqUfS"],
              areas: [],
            },
            bnwVWtmyu8K: {
              id: "bnwVWtmyu8K",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 905.1670000973187,
              y: 1763.2115674130994,
              lines: ["BaD1NopzxM0", "BaD1NopzxM0"],
              areas: [],
            },
            GxXplm1cLrV: {
              id: "GxXplm1cLrV",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1300.5761033139593,
              y: 1097.5588325016324,
              lines: ["GMCmSNzgor", "zrMXJqo0yW0"],
              areas: [],
            },
            mtbvQCOQteT: {
              id: "mtbvQCOQteT",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1300.5761033139593,
              y: 596.896946414375,
              lines: ["zrMXJqo0yW0", "f5C8DF6neE"],
              areas: [],
            },
            NCtIJDeVklN: {
              id: "NCtIJDeVklN",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1599.2664330819252,
              y: 1296.6857190136097,
              lines: ["h4zteZPjvmB", "9Vyygqe59p"],
              areas: [],
            },
            QBGW_2M2Zrm: {
              id: "QBGW_2M2Zrm",
              type: "",
              prototype: "vertices",
              name: "Vertex",
              misc: {},
              selected: false,
              properties: {},
              visible: true,
              x: 1095.759877187354,
              y: 1097.5588325016324,
              lines: ["hjEMx7bqUfS", "RoEx_yqt1G"],
              areas: [],
            },
          },
          lines: {
            RoEx_yqt1G: {
              id: "RoEx_yqt1G",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["_z3Tpxi8Ibq", "QBGW_2M2Zrm"],
              holes: [],
            },
            BaD1NopzxM0: {
              id: "BaD1NopzxM0",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["bnwVWtmyu8K", "bnwVWtmyu8K"],
              holes: [],
            },
            zrMXJqo0yW0: {
              id: "zrMXJqo0yW0",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["mtbvQCOQteT", "GxXplm1cLrV"],
              holes: [],
            },
            "DAB-5Viao2L": {
              id: "DAB-5Viao2L",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["_z3Tpxi8Ibq", "RyNf_IIhaph"],
              holes: [],
            },
            hjEMx7bqUfS: {
              id: "hjEMx7bqUfS",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["Mtxn9_dUm6O", "QBGW_2M2Zrm"],
              holes: [],
            },
            "9Vyygqe59p": {
              id: "9Vyygqe59p",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["RyNf_IIhaph", "NCtIJDeVklN"],
              holes: [],
            },
            h4zteZPjvmB: {
              id: "h4zteZPjvmB",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["InbPjbUTVTp", "NCtIJDeVklN"],
              holes: [],
            },
            GMCmSNzgor: {
              id: "GMCmSNzgor",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["GxXplm1cLrV", "InbPjbUTVTp"],
              holes: [],
            },
            f5C8DF6neE: {
              id: "f5C8DF6neE",
              type: "wall",
              prototype: "lines",
              name: "Mur",
              misc: {},
              selected: false,
              properties: {
                height: { length: 300 },
                thickness: { length: 20 },
                textureA: "bricks",
                textureB: "bricks",
              },
              visible: true,
              vertices: ["Mtxn9_dUm6O", "mtbvQCOQteT"],
              holes: [],
            },
          },
          holes: {},
          areas: {
            "v7Q-o6bOMR6": {
              id: "v7Q-o6bOMR6",
              type: "area",
              prototype: "areas",
              name: "Zone",
              misc: {},
              selected: false,
              properties: {
                patternColor: "#F5F4F4",
                thickness: { length: 0 },
                texture: "none",
              },
              visible: true,
              vertices: [
                "RyNf_IIhaph",
                "_z3Tpxi8Ibq",
                "QBGW_2M2Zrm",
                "Mtxn9_dUm6O",
                "mtbvQCOQteT",
                "GxXplm1cLrV",
                "InbPjbUTVTp",
                "NCtIJDeVklN",
              ],
              holes: [],
            },
          },
          items: {},
          selected: {
            vertices: [],
            lines: [],
            holes: [],
            areas: [],
            items: [],
          },
        },
      },
      grids: {
        h1: {
          id: "h1",
          type: "horizontal-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
        v1: {
          id: "v1",
          type: "vertical-streak",
          properties: {
            step: 20,
            colors: ["#808080", "#ddd", "#ddd", "#ddd", "#ddd"],
          },
        },
      },
      selectedLayer: "layer-1",
      groups: {},
      width: 3000,
      height: 2000,
      meta: {},
      guides: { circular: {}, vertical: {}, horizontal: {} },
    },
  },
];

// Helper function to get template by ID
export function getTemplate(id: string): PlanTemplate | undefined {
  return PLAN_TEMPLATES.find((template) => template.id === id);
}

// Helper function to get all templates except empty (for selection)
export function getStarterTemplates(): PlanTemplate[] {
  return PLAN_TEMPLATES.filter((template) => template.id !== "empty");
}
